// Generated by CoffeeScript 1.9.3
var Promise, Xhr, XhrPromise, serialize,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

Xhr = require('httpify');

Promise = (require('es6-promise')).Promise;

serialize = function(obj, prefix) {
  var k, p, str, v;
  if (!obj) {
    return "";
  }
  str = [];
  for (p in obj) {
    if (obj.hasOwnProperty(p)) {
      k = prefix ? prefix + "[" + p + "]" : p;
      v = obj[p];
      str.push(typeof v === "object" ? serialize(v, k) : encodeURIComponent(k) + "=" + encodeURIComponent(v));
    }
  }
  return str.join("&");
};

XhrPromise = (function() {
  function XhrPromise() {
    this.getJsons = bind(this.getJsons, this);
  }

  XhrPromise.prototype.getJson = function(url, params) {
    var p;
    p = new Promise(function(resolve, reject) {
      return Xhr({
        timout: 2000,
        method: 'get',
        uri: encodeURI(url) + (params ? "?" + serialize(params) : ""),
        headers: {
          "Accept": "application/json"
        }
      }, function(err, resp, body) {
        if (err === null) {
          return resolve(resp.body);
        } else {
          return reject(err);
        }
      });
    });
    return p;
  };

  XhrPromise.prototype.getJsons = function(urls) {
    var promises;
    promises = urls.map((function(_this) {
      return function(url) {
        return _this.getJson(url);
      };
    })(this));
    return Promise.all(promises);
  };

  return XhrPromise;

})();

module.exports = new XhrPromise();
